---
plugin: aws_ec2
aws_access_key: AKIAV222A3F7LMSULWP2
aws_secret_key: 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
#compose:
#  ansible_host: public_ip_address
#regions:
#  - us-west-2
#filters:
#  tag:Name: genesis