- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Wait 60 seconds, but only start checking after 10 seconds
      wait_for_connection:
        delay: 10
        timeout: 60

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  roles:
    - roles/install_nginx

  tasks:
    - name: restart nginx
      shell: service nginx reload
  
